[package]
name = "rnacli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
reqwest = "0.12.24"
rnaapi = "0.3.2"
serde = { version = "1.0.228", features = ["derive", "default"] }
serde_json = "1.0.145"
tokio = { version = "1.48.0", features = ["full"] }
